version: "3.3"

services:
  vesta:
    image: niiknow/vestacp
    container_name: vesta
    cap_add: ['NET_RAW', 'NET_ADMIN']
    environment:
      - "VESTA_DOMAIN=your-vesta.panel-dns.com"
    volumes:
      - "./backup:/backup"
      - "./vesta:/vesta"
      - "./home:/home"
    ports:
      - "2222:22"
      - "81:80"
      - "443:443"
      - "8083:8083"
    labels:
      - "Vesta Control Panel"
    restart: unless-stopped
